In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from src.download_save_load import get_chess_dataframes, download_chess_games

download_chess_games("ParpasP")

games_df, moves_df = get_chess_dataframes("ParpasP")

✓ File already exists: c:\Users\user\Documents\Stats\Chess-Project\data\raw\ChessGames_ParpasP.json
  To download fresh data, use force_download=True
🔍 Looking for existing dataframes for ParpasP...
✓ Loaded 2426 games and 151079 moves from csv files

In [3]:
from src.cache import run_chess_analysis
import asyncio

asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())

# result_df, moves_df = run_chess_analysis(games_df, moves_df, time_control=None, n_games=500, depth=10) #if not all games, to get the filtered dataframe
result_df, moves_df = run_chess_analysis(
    games_df, moves_df, time_control=None, n_games=-1, depth=10
)

C:\Users\user\AppData\Local\Temp\ipykernel_81720\1444030581.py:4: DeprecationWarning: 'asyncio.WindowsProactorEventLoopPolicy' is deprecated and slated for removal in Python 3.16
  asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
C:\Users\user\AppData\Local\Temp\ipykernel_81720\1444030581.py:4: DeprecationWarning: 'asyncio.set_event_loop_policy' is deprecated and slated for removal in Python 3.16
  asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())

✅ Games selected: 2426
✅ Moves selected: 151079
Loaded 151079 cached evaluations

Analyzing moves:   0%|          | 0/151079 [00:00<?, ?move/s]

💾 Saved 151079 evaluations to cache

==================================================
Total moves analyzed: 151079
Games analyzed: 2424
Cache hits: 151079
New evaluations: 0
Cache size: 151079 total entries

In [4]:
result_df

,link_id,uuid,move_index,move_no,player,move,clock_before,clock_after,thinking_time,my_move,eval_before,eval_after,delta,blunder,blunder_type,move_type,fen,end_time
13029,170090456418,16e600e5-6668-11f1-88e6-aebfe201000f,0,1,white,d4,180.0,181.3,0.7,True,0,34,34,0,no_blunder,Best,rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR ...,1781273730
13030,170090456418,16e600e5-6668-11f1-88e6-aebfe201000f,1,1,black,g6,180.0,180.1,1.9,False,34,63,-29,0,no_blunder,Excellent,rnbqkbnr/pppppp1p/6p1/8/3P4/8/PPP1PPPP/RNBQKBN...,1781273730
13031,170090456418,16e600e5-6668-11f1-88e6-aebfe201000f,2,2,white,c4,181.3,182.9,0.4,True,63,51,-12,0,no_blunder,Excellent,rnbqkbnr/pppppp1p/6p1/8/2PP4/8/PP2PPPP/RNBQKBN...,1781273730
13032,170090456418,16e600e5-6668-11f1-88e6-aebfe201000f,3,2,black,Bg7,180.1,180.1,2.0,False,51,56,-5,0,no_blunder,Best,rnbqk1nr/ppppppbp/6p1/8/2PP4/8/PP2PPPP/RNBQKBN...,1781273730
13033,170090456418,16e600e5-6668-11f1-88e6-aebfe201000f,4,3,white,Nc3,182.9,184.6,0.3,True,56,50,-6,0,no_blunder,Best,rnbqk1nr/ppppppbp/6p1/8/2PP4/2N5/PP2PPPP/R1BQK...,1781273730
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137903,121117316976,e71d2c48-ac29-11ef-92d2-02107401000f,36,19,white,Rf8+,28.3,26.2,4.1,True,-213,-297,-84,0,no_blunder,Inaccuracy,r1bk1R2/ppp4p/3p4/8/8/b2P4/P1Pn2PP/4R2K b - - ...,1732648585
137904,121117316976,e71d2c48-ac29-11ef-92d2-02107401000f,37,19,black,Kd7,9.4,7.0,4.4,False,-297,-261,-36,0,no_blunder,Good,r1b2R2/pppk3p/3p4/8/8/b2P4/P1Pn2PP/4R2K w - - ...,1732648585
137905,121117316976,e71d2c48-ac29-11ef-92d2-02107401000f,38,20,white,Rf2,26.2,21.4,6.8,True,-261,-368,-107,0,no_blunder,Mistake,r1b5/pppk3p/3p4/8/8/b2P4/P1Pn1RPP/4R2K b - - 3 20,1732648585
137906,121117316976,e71d2c48-ac29-11ef-92d2-02107401000f,39,20,black,Bb4,7.0,2.8,6.2,False,-368,-317,-51,0,no_blunder,Inaccuracy,r1b5/pppk3p/3p4/8/1b6/3P4/P1Pn1RPP/4R2K w - - ...,1732648585
137907,121117316976,e71d2c48-ac29-11ef-92d2-02107401000f,40,21,white,Rc1,21.4,13.3,10.1,True,-317,-436,-119,0,no_blunder,Mistake,r1b5/pppk3p/3p4/8/1b6/3P4/P1Pn1RPP/2R4K b - - ...,1732648585

In [5]:
from src.puzzle import generate_chess_puzzles

puzzles_df = generate_chess_puzzles(result_df)

HERE

In [6]:
from src.puzzle import reevaluate_puzzles

puzzles_df = reevaluate_puzzles(puzzles_df)

Analyzing moves with higher depth:   0%|          | 0/2248 [00:00<?, ?move/s]

In [7]:
puzzles_df

,uuid,link_id,type,move_no,my_color,fen_before,fen_after,move_before,move_curr,played_move,eval_before,eval_after,clock_before,clock_after,thinking_time,eval_before_hd,eval_after_hd
0,00795940-2240-11f1-ba3a-0480d301000f,166081612344,my_blunder,48,white,8/8/1p6/p1p2Kp1/2Pp4/P5P1/7k/3B4 w - - 0 48,8/8/1p6/p1p3K1/2Pp4/P5P1/7k/3B4 b - - 0 48,g2h2,f5g5,Kxg5,426,19,3.4,3.8,0.6,426,19
1,00aaacdf-8656-11f0-8385-93dc4f01000f,142551833498,opponent_blunder,6,black,rnbqkb1r/pB3ppp/5n2/2p5/8/5Q2/PPPP1PPP/RNB1K1N...,rn1qkb1r/pb3ppp/5n2/2p5/8/5Q2/PPPP1PPP/RNB1K1N...,d5b7,c8b7,Bxb7,-334,177,183.8,180.2,5.6,-334,177
2,00de250f-d399-11ef-a106-d377a001000f,122172444578,my_blunder,8,black,r1bq3r/ppp2kpp/2n5/2bBp3/4P3/8/PPPP1PPP/R1BQK2...,r1bq3r/ppp1k1pp/2n5/2bBp3/4P3/8/PPPP1PPP/R1BQK...,c4d5,f7e7,Ke7,-284,225,126.2,120.0,8.2,-284,225
3,016df6a4-6110-11f0-91b1-f23cba01000f,140704192918,my_blunder,15,white,r4rk1/pbpn1pp1/1p2p2p/n3P1q1/2BP1N2/2P5/P3QPPP...,r4rk1/pbpn1pp1/1p2B2p/n3P1q1/3P1N2/2P5/P3QPPP/...,c6a5,c4e6,Bxe6,170,-366,116.7,114.6,4.1,170,-366
4,016df6a4-6110-11f0-91b1-f23cba01000f,140704192918,my_blunder,16,white,r4rk1/pbpn2p1/1p2p2p/n3P1q1/3P1N2/2P5/P3QPPP/R...,r4rk1/pbpn2p1/1p2N2p/n3P1q1/3P4/2P5/P3QPPP/R1B...,f7e6,f4e6,Nxe6,-316,-10000,114.6,115.5,1.1,-316,-10000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2243,fefbbe11-fd40-11ef-8c97-9c00a101000f,136092505876,my_blunder,11,black,r3kb1r/pp2Nppp/8/3p4/8/8/PPPPQPqP/RNB1K2R b KQ...,r3k2r/pp2bppp/8/3p4/8/8/PPPPQPqP/RNB1K2R w KQk...,c6e7,f8e7,Bxe7,-354,226,892.8,902.1,0.7,-354,226
2244,ff34f4ce-1be4-11f1-b615-44583801000f,165727273158,my_blunder,11,black,2rqk1nr/pp1b1ppp/3Bp1n1/1Nbp4/8/8/PPP1BPPP/RN1...,2rqk2r/pp1bnppp/3Bp1n1/1Nbp4/8/8/PPP1BPPP/RN1Q...,f4d6,g8e7,N8e7,-264,258,143.9,136.8,9.1,-264,258
2245,ff84a960-035a-11f1-91b0-a5288401000f,164314549838,my_blunder,29,black,6k1/8/1p2p2p/5p2/2Br1P2/8/rPR2K1P/8 b - - 1 29,6k1/8/1p2p2p/5p2/2B1rP2/8/rPR2K1P/8 w - - 2 30,d3c4,d4e4,Re4,-407,247,22.4,16.9,7.5,-407,247
2246,ffb63a2b-e650-11f0-8085-d502c301000f,147410911658,my_blunder,31,black,2r2rk1/1Q3ppp/8/8/1P4q1/6P1/3NnPKP/1R1R4 b - -...,5rk1/1Q3ppp/8/8/1P4q1/6P1/2rNnPKP/1R1R4 w - - ...,g1g2,c8c2,Rc2,-188,123,20.4,18.4,2.0,-188,123
2247,ffe072d3-13f5-11f0-a0dd-ce543c01000f,137137795536,my_blunder,25,black,2r1k2r/p1P2pRp/4b3/1B1p1p2/5q2/P4p2/5P2/2RQK3 ...,2r1k2r/p1Pb1pRp/8/1B1p1p2/5q2/P4p2/5P2/2RQK3 w...,f1b5,e6d7,Bd7,-314,329,32.1,26.1,11.0,-314,329

In [8]:
result_df

,link_id,uuid,move_index,move_no,player,move,clock_before,clock_after,thinking_time,my_move,eval_before,eval_after,delta,blunder,blunder_type,move_type,fen,end_time
13029,170090456418,16e600e5-6668-11f1-88e6-aebfe201000f,0,1,white,d4,180.0,181.3,0.7,True,0,34,34,0,no_blunder,Best,rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR ...,1781273730
13030,170090456418,16e600e5-6668-11f1-88e6-aebfe201000f,1,1,black,g6,180.0,180.1,1.9,False,34,63,-29,0,no_blunder,Excellent,rnbqkbnr/pppppp1p/6p1/8/3P4/8/PPP1PPPP/RNBQKBN...,1781273730
13031,170090456418,16e600e5-6668-11f1-88e6-aebfe201000f,2,2,white,c4,181.3,182.9,0.4,True,63,51,-12,0,no_blunder,Excellent,rnbqkbnr/pppppp1p/6p1/8/2PP4/8/PP2PPPP/RNBQKBN...,1781273730
13032,170090456418,16e600e5-6668-11f1-88e6-aebfe201000f,3,2,black,Bg7,180.1,180.1,2.0,False,51,56,-5,0,no_blunder,Best,rnbqk1nr/ppppppbp/6p1/8/2PP4/8/PP2PPPP/RNBQKBN...,1781273730
13033,170090456418,16e600e5-6668-11f1-88e6-aebfe201000f,4,3,white,Nc3,182.9,184.6,0.3,True,56,50,-6,0,no_blunder,Best,rnbqk1nr/ppppppbp/6p1/8/2PP4/2N5/PP2PPPP/R1BQK...,1781273730
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137903,121117316976,e71d2c48-ac29-11ef-92d2-02107401000f,36,19,white,Rf8+,28.3,26.2,4.1,True,-213,-297,-84,0,no_blunder,Inaccuracy,r1bk1R2/ppp4p/3p4/8/8/b2P4/P1Pn2PP/4R2K b - - ...,1732648585
137904,121117316976,e71d2c48-ac29-11ef-92d2-02107401000f,37,19,black,Kd7,9.4,7.0,4.4,False,-297,-261,-36,0,no_blunder,Good,r1b2R2/pppk3p/3p4/8/8/b2P4/P1Pn2PP/4R2K w - - ...,1732648585
137905,121117316976,e71d2c48-ac29-11ef-92d2-02107401000f,38,20,white,Rf2,26.2,21.4,6.8,True,-261,-368,-107,0,no_blunder,Mistake,r1b5/pppk3p/3p4/8/8/b2P4/P1Pn1RPP/4R2K b - - 3 20,1732648585
137906,121117316976,e71d2c48-ac29-11ef-92d2-02107401000f,39,20,black,Bb4,7.0,2.8,6.2,False,-368,-317,-51,0,no_blunder,Inaccuracy,r1b5/pppk3p/3p4/8/1b6/3P4/P1Pn1RPP/4R2K w - - ...,1732648585
137907,121117316976,e71d2c48-ac29-11ef-92d2-02107401000f,40,21,white,Rc1,21.4,13.3,10.1,True,-317,-436,-119,0,no_blunder,Mistake,r1b5/pppk3p/3p4/8/1b6/3P4/P1Pn1RPP/2R4K b - - ...,1732648585

In [9]:
games_df

,uuid,link_id,link,time_class,time_control,rated,white,white_rating,black,black_rating,...,simple_opening,eco_code,my_color,result,raw_result,white_accuracy,black_accuracy,Time,end_time,moves
0,16e600e5-6668-11f1-88e6-aebfe201000f,170090456418,https://www.chess.com/game/live/170090456418,blitz,180+2,True,ParpasP,1119,meladak,1116,...,King's Indian Defense,/www.chess.com/openings/Kings-Indian-Defense-N...,White,Win,win,76.30,77.90,2026-06-12 16:15:30+02:00,1781273730,d4|g6|c4|Bg7|Nc3|d6|e4|Nf6|h3|O-O|Nf3|Nbd7|Bd3...
1,cd802251-6666-11f1-a4a0-df540901000f,170090036116,https://www.chess.com/game/live/170090036116,blitz,180+2,True,Femcme,1147,ParpasP,1111,...,Sicilian Defense,/www.chess.com/openings/Sicilian-Defense-Open-...,Black,Loss,timeout,71.45,65.14,2026-06-12 16:06:46+02:00,1781273206,e4|c5|Nf3|Nc6|d4|cxd4|Nxd4|e5|Nb5|Nf6|Bg5|Be7|...
2,d719861a-6665-11f1-a4a0-df540901000f,170089724238,https://www.chess.com/game/live/170089724238,blitz,180+2,True,Sherv1,1132,ParpasP,1119,...,Slav Defense,/www.chess.com/openings/Slav-Defense-Modern-Ex...,Black,Loss,timeout,NaN,NaN,2026-06-12 15:58:31+02:00,1781272711,d4|d5|c4|c6|cxd5|cxd5|Nc3|Nf6|Nf3|Nc6|Bg5|e6|a...
3,a1047564-6665-11f1-a536-c0b69601000f,170089655612,https://www.chess.com/game/live/170089655612,blitz,180+2,True,ParpasP,1127,EndgameRookMaster,1159,...,Englund Gambit,/www.chess.com/openings/Englund-Gambit-2.dxe5-...,White,Win,win,90.75,79.94,2026-06-12 15:51:00+02:00,1781272260,d4|e5|dxe5|Nc6|Nf3|Qe7|Bf4|Qb4+|Bd2|Qxb2|Nc3|N...
4,e0f9dce9-6664-11f1-88e6-aebfe201000f,170089414082,https://www.chess.com/game/live/170089414082,blitz,180+2,True,IgorLukashevich,1147,ParpasP,1118,...,Sicilian Defense,/www.chess.com/openings/Sicilian-Defense-Frenc...,Black,Loss,checkmated,87.03,68.49,2026-06-12 15:49:27+02:00,1781272167,e4|c5|Nf3|e6|d4|cxd4|Qxd4|Nc6|Qd1|Nf6|e5|Nxe5|...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2421,4eb450cf-bc9a-11ef-8893-df8f3801000f,121529953114,https://www.chess.com/game/live/121529953114,rapid,600,True,ParpasP,271,Ahmet53598,463,...,French Defense,/www.chess.com/openings/French-Defense-Kings-I...,White,Loss,timeout,NaN,NaN,2024-12-17 18:29:39+01:00,1734456579,e4|e6|d3|d5|e5|Bb4+|c3|f6|cxb4|fxe5|Nf3|e4|Bg5...
2422,874dac52-bc98-11ef-aa66-6dda8e01000f,121529692026,https://www.chess.com/game/live/121529692026,blitz,180+2,True,Andrewdobtplaywithme,318,ParpasP,438,...,King's Pawn Opening,/www.chess.com/openings/Kings-Pawn-Opening-1...e5,Black,Win,win,62.02,69.30,2024-12-17 18:08:38+01:00,1734455318,e4|e5|f3|Qh4+|g3|Qe7|f4|exf4|gxf4|Qxe4+|Qe2|Qx...
2423,5b88d5e0-ac2b-11ef-a187-ae657801000f,121117490854,https://www.chess.com/game/live/121117490854,blitz,180+2,True,ParpasP,370,miphtahusseyn,551,...,Pirc Defense,/www.chess.com/openings/Pirc-Defense-Main-Line...,White,Loss,timeout,NaN,NaN,2024-11-26 20:25:32+01:00,1732649132,d4|Nf6|Nc3|g6|e4|d6|f3|Bg7|Be3|O-O|Bd3|Nc6|Nge...
2424,15c46c40-ac2b-11ef-997c-4978a401000f,121117458476,https://www.chess.com/game/live/121117458476,blitz,180+2,True,miphtahusseyn,545,ParpasP,432,...,Italian Game,/www.chess.com/openings/Italian-Game-Knight-At...,Black,Loss,resigned,NaN,NaN,2024-11-26 20:19:14+01:00,1732648754,e4|e5|Nf3|Nc6|Bc4|Nf6|Ng5|d5|exd5|Nxd5|Nxf7|Kx...
2425,e71d2c48-ac29-11ef-92d2-02107401000f,121117316976,https://www.chess.com/game/live/121117316976,blitz,180+2,True,ParpasP,556,FaiZan-RajA,352,...,King's Gambit,/www.chess.com/openings/Kings-Gambit-Declined-...,White,Win,win,65.19,74.47,2024-11-26 20:16:25+01:00,1732648585,e4|e5|f4|Nc6|Nf3|Nd4|Bc4|exf4|Bxf7+|Kxf7|Ne5+|...

In [11]:
list(games_df["opening"].unique())

['Kings-Indian-Defense-Normal-Variation...5.Nf3-O-O-6.h3-Nbd7',
 'Sicilian-Defense-Open-Lowenthal-Variation-5.Nb5-Nf6',
 'Slav-Defense-Modern-Exchange-Variation-4...cxd5-5.Nc3-Nc6',
 'Englund-Gambit-2.dxe5-Nc6-3.Nf3-Qe7',
 'Sicilian-Defense-French-Variation-3.d4-cxd4',
 'Queens-Gambit-Declined-Baltic-Defense',
 'Sicilian-Defense-French-Variation',
 'Queens-Gambit-Declined-Exchange-Positional-Line',
 'Sicilian-Defense-Open-Lowenthal-Variation-5.Nb5',
 'English-Opening-Kings-English-Variation...3.Bg2-d5-4.cxd5-Nxd5',
 'English-Opening-Anglo-Indian-Anglo-Grunfeld-Defense...5.e4-Nb6-6.d4-Bg7',
 'Indian-Game-East-Indian-Defense-3.Nc3',
 'Sicilian-Defense-Smith-Morra-Gambit...3.Qxd4-Nc6-4.Qd1-Nf6',
 'Sicilian-Defense-Bowdler-Attack-2...e6-3.Nc3-Nc6',
 'Queens-Gambit-Declined-Marshall-Defense-3.cxd5-Nxd5-4.e4-Nb6-5.Nc3',
 'Sicilian-Defense-McDonnell-Attack-2...Nc6-3.Nf3',
 'Benoni-Defense-Modern-Kings-Pawn-Line',
 'Englund-Gambit-2.dxe5',
 'Kings-Indian-Defense-Makogonov-Variation',
 'Queens-Pawn-Opening-Chigorin-Variation-2...Nf6-3.Bf4-c5-4.e3',
 'Polish-Opening-1...Nf6-2.Bb2-d5-3.e3',
 'Queens-Pawn-Opening-Symmetrical-Variation-3.c4-c5',
 'Sicilian-Defense-Smith-Morra-Gambit-Accepted-4.Nxc3-Nc6-5.Nf3',
 'Sicilian-Defense-Open-Lowenthal-Variation-5.Nxc6-bxc6',
 'Slav-Defense-3.Nc3',
 'Queens-Pawn-Opening-Accelerated-London-Steinitz-Countergambit',
 'Queens-Gambit-Declined-Exchange-Positional-Line...6.Nf3-Be7-7.e3-O-O-8.Bd3',
 'Alapin-Sicilian-Defense...3.Nf3-Nc6-4.d4-cxd4-5.cxd4',
 'Sicilian-Defense-Bowdler-Attack-2...e6',
 'Queens-Gambit-Accepted-Central-Variation-Greco-Variation-4.a4-c6-5.axb5-cxb5',
 'Queens-Pawn-Opening-Accelerated-London-Steinitz-Countergambit-3.e3-Nc6',
 'Sicilian-Defense-Old-Sicilian-Variation-3.Bc4-e6',
 'Slav-Defense-3.Nc3-Nf6-4.Bg5',
 'Queens-Gambit-Accepted-Central-Variation',
 'London-System...4.e3-Bf5-5.c4-e6-6.Nc3',
 'Queens-Gambit-Declined-Marshall-Defense-3.cxd5-Nxd5-4.e4-Nf6-5.Nc3',
 'French-Defense-Exchange-Monte-Carlo-Variation...5.Nc3-c6-6.Nf3-Be7',
 'Queens-Pawn-Opening-Accelerated-London-Steinitz-Countergambit-3.e3-Nc6-4.Nf3',
 'Modern-Defense-with-1-d4-2.c4-Bg7-3.Nc3',
 'Queens-Pawn-Opening-Mikenas-Defense-2.c4-e5',
 'Closed-Sicilian-Defense-2...e6-3.d3',
 'Queens-Gambit-Declined-Baltic-Deferred-Queen-Attack',
 'Queens-Pawn-Opening-Blackmar-Gambit-2...dxe4',
 'Queens-Gambit-Declined-Queens-Knight-Variation-3...dxc4-4.e4',
 'Queens-Gambit-Declined-Chigorin-Janowski-Variation...6.Be3-e6-7.Bxc4-Bb4',
 'Slav-Defense-Modern-Two-Knights-Attack',
 'Van-Geet-Opening-Reversed-Nimzowitsch-Variation-2.b3',
 'Sicilian-Defense-Taimanov-Variation-5.Nc3',
 'Sicilian-Defense-French-Variation-3.Nc3-Nc6',
 'Queens-Gambit-Declined-Semi-Slav-Defense-Accelerated-Move-Order-4.e4-Bb4-5.cxd5',
 'Sicilian-Defense-Old-Sicilian-Variation-3.Bc4-e6-4.Nc3',
 'Slav-Defense-Modern-Three-Knights-Variation',
 'Queens-Pawn-Opening-1...c6-2.c4',
 'Queens-Gambit-Declined-Austrian-Variation',
 'Queens-Pawn-Opening-English-Defense-3.Nc3-Bb7-4.e4',
 'Colle-System-3...c6-4.Bd3',
 'Queens-Pawn-Opening-Horwitz-Defense-2.c4',
 'Slav-Defense-3.Nc3-Nf6',
 'Queens-Gambit-Declined-Queens-Knight-Variation',
 'Queens-Gambit-Declined-Marshall-Defense-3.cxd5',
 'Mieses-Opening-1...c5',
 'English-Opening-1...d6-2.d4',
 'Undefined',
 'Queens-Gambit-Declined-Zilbermints-Gambit',
 'Indian-Game-2.c3',
 'Slav-Defense-Slav-Gambit-Alekhine-Attack-4...b5-5.a4',
 'Van-t-Kruijs-Opening-1...c5',
 'Closed-Sicilian-Defense-2...e6',
 'Kings-Indian-Defense-Normal-Variation-4.e4-d6-5.Nf3-O-O-6.h3',
 'Sicilian-Defense-Smith-Morra-Gambit-2...cxd4-3.Qxd4-Nc6-4.Qd1',
 'Sicilian-Defense-Taimanov-Variation-5.Nxc6-bxc6-6.c4',
 'Queens-Gambit-Declined-Marshall-Defense...4.e4-Nf6-5.Nc3-e6',
 'Sicilian-Defense-Taimanov-Variation-5.Nxc6-bxc6-6.Bd3-d5',
 'Alapin-Sicilian-Defense...4.d4-cxd4-5.cxd4-d5',
 'Queens-Pawn-Opening-Horwitz-Defense...3.c4-Nf6-4.Nc3-Bb4',
 'Slav-Defense-Modern-Alapin-Variation-Czech-Classical-Dutch-Variation-8...Nbd7',
 'Old-Benoni-Defense-2.d5',
 'Sicilian-Defense',
 'Slav-Defense-Slav-Gambit-Alekhine-Attack',
 'Queens-Pawn-Opening-Horwitz-Defense...3.c4-Nf6-4.Nc3-Be7',
 'Mieses-Opening',
 'Queens-Gambit-Declined-Marshall-Defense-3.cxd5-Qxd5-4.Nc3',
 'Queens-Pawn-Opening-Zukertort-Chigorin-Variation-3.Bf4-Nf6-4.e3',
 'Old-Benoni-Defense-2.dxc5',
 'Queens-Gambit-Accepted-Central-Variation-Alekhine-System-4.e5',
 'Sicilian-Defense-2.d3-d5',
 'Mieses-Opening-1...d5',
 'Queens-Pawn-Opening-English-Rat-Defense-3.dxe5',
 'Kings-Pawn-Opening-Leonardis-Variation-2...Nf6',
 'Queens-Pawn-Opening-Keres-Transpositional-Variation',
 'Queens-Gambit-Declined-Chigorin-Defense-3.Nf3-e6-4.Nc3-Nf6-5.Bg5',
 'Sicilian-Defense-French-Variation...4.Bb5-Nd4-5.Nxd4-cxd4',
 'Englund-Gambit',
 'Queens-Pawn-Opening-1...d5-2.c3',
 'Queens-Gambit-Declined-Chigorin-Janowski-Variation',
 'Queens-Gambit-Declined-Exchange-Variation-4...Nxd5-5.e4',
 'Queens-Gambit-Declined-Exchange-Positional-Line...6.e3-h6-7.Bh4-O-O-8.Bd3',
 'Alapin-Sicilian-Defense-2...e6-3.d4-cxd4-4.cxd4',
 'Queens-Gambit',
 'Sicilian-Defense-Mengarini-Variation-2...Nc6-3.b4',
 'Queens-Gambit-Declined-Exchange-Positional-Line-5...Nbd7',
 'Slav-Defense-3.e3-Nf6',
 'Kings-Indian-Defense-Normal-Variation...5.Nf3-O-O-6.h3-c5',
 'Kings-Indian-Defense-Normal-Variation...7.dxe5-dxe5-8.Qxd8-Rxd8',
 'Sicilian-Defense-Nyezhmetdinov-Rossolimo-Attack-3...Nd4',
 'Queens-Pawn-Opening-Krause-Variation-3.c3-Nc6',
 'Queens-Indian-Defense-Kasparov-Variation-4...Bb7-5.Bg5-Be7-6.e3',
 'Dutch-Defense-Classical-Rubinstein-Variation-3...Nf6-4.Bg5-Bb4',
 'Scandinavian-Defense-Mieses-Kotrc-Gubinsky-Melts-Defense-4.Nf3-Nf6',
 'Queens-Gambit-Declined-Semi-Slav-Defense-Accelerated-Move-Order',
 'Queens-Pawn-Opening-Krause-Variation-3.e3',
 'Queens-Gambit-Declined-Queens-Knight-Variation-3...Bb4-4.Nf3',
 'Slav-Defense-Modern-Line...4.g3-Bf5-5.Bg2-e6-6.Nc3',
 'Sicilian-Defense-French-Variation-3.Nc3-Nc6-4.Bb5-Nd4',
 'Queens-Gambit-Declined-Exchange-Positional-Line-5...Be7-6.e3',
 'Alapin-Sicilian-Defense-2...Nc6-3.d4-cxd4-4.cxd4',
 'Benoni-Defense-Hromadka-System-4.Nc3',
 'Sicilian-Defense-Old-Sicilian-Variation-3.b3-d6-4.Bb2',
 'Queens-Pawn-Opening-Chigorin-Variation-2...Nf6-3.Nf3',
 'Queens-Gambit-Declined-Queens-Knight-Variation-3...Bb4',
 'Queens-Pawn-Opening-Stonewall-Attack-3...c5-4.c3-Nc6',
 'Slav-Defense-Modern-Geller-Gambit-5...b5',
 'Queens-Pawn-Opening-1...d5-2.e3-c5',
 'Slav-Defense-Modern-Line-3...Nf6',
 'Queens-Pawn-Opening-Mikenas-Defense-2.d5',
 'English-Opening-Symmetrical-Three-Knights-System-3...d5-4.cxd5-Nxd5-5.e3',
 'Reti-Opening-Sicilian-Invitation...4.d3-d5-5.O-O-Nf6',
 'Englund-Gambit-2.dxe5-Nc6-3.Nf3',
 'Queens-Pawn-Opening-Horwitz-Defense...5.g3-b6-6.Bg2-Bb7-7.O-O',
 'Queens-Gambit-Declined-Modern-Variation...6.Nf3-Ne4-7.Bxe7-Qxe7',
 'Sicilian-Defense-Westerinen-Attack-3...Nc6-4.Bb2-d5-5.exd5',
 'Queens-Pawn-Opening-Zukertort-Variation-2...c6-3.e3-Bf5-4.Bd3',
 'Queens-Gambit-Declined-Chigorin-Janowski-Variation-4...Nf6-5.e4',
 'Queens-Gambit-Declined-Exchange-Variation-4...Nxd5-5.e4-Nxc3-6.bxc3',
 'Sicilian-Defense-Taimanov-Variation-5.Nxc6-bxc6',
 'Queens-Pawn-Opening-English-Defense-3.Nc3-Bb4-4.e4-Bb7',
 'Queens-Gambit-Declined-Exchange-Positional-Line-5...Be7-6.e3-O-O-7.Bd3',
 'Queens-Gambit-Declined-Semi-Slav-Defense-Accelerated-Move-Order-4.e4-dxe4-5.Nxe4',
 'Scandinavian-Defense-Mieses-Kotrc-Variation',
 'Sicilian-Defense-Nyezhmetdinov-Rossolimo-Attack-3...Nd4-4.Nxd4-cxd4-5.O-O',
 'Indian-Game-East-Indian-Benoni-Defense',
 'Slav-Defense-Modern-Triangle-Noteboom-Variation-5.e4-b5-6.a4',
 'French-Defense-Kings-Indian-Attack-2...c5',
 'Scandinavian-Defense-Mieses-Kotrc-Main-Line-4.d4-Nf6-5.Nf3-Nc6-6.Bd2',
 'Slav-Defense-Exchange-Variation-3...cxd5-4.Nc3-Nc6',
 'Slav-Defense-Exchange-Symmetrical-Line',
 'Queens-Pawn-Opening-Krause-Variation-3.e3-Nc6',
 'Old-Benoni-Defense',
 'Grunfeld-Defense-Exchange-Variation-5.e4-Nxc3-6.bxc3-Bg7',
 'Indian-Game-Black-Knights-Tango-3.d5-Ne5',
 'Sicilian-Defense-Open-Lowenthal-Variation',
 'Scandinavian-Defense-Closed-2...d4',
 'Slav-Defense-Exchange-Variation-3...cxd5-4.Nc3-Nf6',
 'Queens-Gambit-Declined-Modern-Variation...5.e3-h6-6.Bh4-O-O',
 'Indian-Game...3.e3-c5-4.c3-Nc6',
 'Queens-Gambit-Accepted-Central-Variation-McDonnell-Defense',
 'French-Defense-Advance-Nimzowitsch-System',
 'Sicilian-Defense-Staunton-Cochrane-Variation...5.Bg2-d6-6.d3-Nf6',
 'Slav-Defense-3.Nc3-Nf6-4.e3-Bf5-5.Nf3',
 'Queens-Pawn-Opening-1...d5-2.e3-Nf6',
 'Queens-Gambit-Declined-Marshall-Defense',
 'Queens-Pawn-Opening...2.c4-Nd7-3.Nc3-e5',
 'Kings-Fianchetto-Opening-Sicilian-Invitation-2.Bg2',
 'Reti-Opening-Kings-Indian-Attack-2...c5-3.Bg2-Nc6',
 'Queens-Gambit-Declined-Modern-Knight-Defense-5.e3-c6-6.Nf3',
 'Sicilian-Defense-Taimanov-Variation-5.Nc3-Bb4',
 'Sicilian-Defense-Smith-Morra-Gambit-Accepted-4.Nxc3-Nc6',
 'Queens-Gambit-Declined-Baltic-Defense...4.Nf3-Nf6-5.Bg5-c6',
 'Queens-Gambit-Declined-Marshall-Defense-3.cxd5-Qxd5',
 'Queens-Pawn-Opening-Polish-Defense-2.e4',
 'Slav-Defense-Modern-Quiet-Schallopp-Defense',
 'Queens-Pawn-Opening-Horwitz-Defense-2.c4-c5-3.d5',
 'Queens-Gambit-Declined-Albin-Countergambit-3.dxe5-d4-4.Nf3',
 'Queens-Pawn-Opening-Stonewall-Attack',
 'Queens-Gambit-Declined-Exchange-Positional-Line-5...Be7',
 'English-Opening-Agincourt-Defense-2.Nc3-Nf6',
 'English-Opening-Symmetrical-Variation-2.Nf3-Nc6-3.d4-cxd4',
 'Queens-Gambit-Declined-Exchange-Positional-Line-5...Be7-6.e3-h6-7.Bh4',
 'Semi-Slav-Defense-Main-Line',
 'Kings-Indian-Attack-Sicilian-Variation-3.Bg2-Nf6-4.O-O-Nc6',
 'Old-Benoni-Defense-2.e3-cxd4-3.exd4',
 'London-System-3...c6-4.e3-Bf5',
 'Modern-Defense-3.Nc3-Bg7-4.Nf3-Nc6',
 'Sicilian-Defense-Nyezhmetdinov-Rossolimo-Attack-3...e6',
 'Queens-Gambit-Declined-Queens-Knight-Variation-3...Nf6',
 'Queens-Gambit-Accepted-Central-Variation-Rubinstein-Defense-4.Nf3',
 'Sicilian-Defense-French-Variation...6.Bg2-Be7-7.O-O-O-O',
 'Queens-Gambit-Declined-Three-Knights-Vienna-Variation-5.Bg5',
 'Queens-Pawn-Opening-Horwitz-Defense-2.c4-c5',
 'Sicilian-Defense-Open-Pelikan-and-Sveshnikov-Retreat-Variation-6...Bb4',
 'Old-Benoni-Defense-2.d5-e6',
 'Indian-Game-2.Bf4-e6-3.e3-d5-4.Nf3',
 'Sicilian-Defense-French-Variation...4.Bb5-Nd4-5.Nxd4-cxd4-6.Ne2',
 'Tarrasch-Defense',
 'Modern-Defense-with-1-d4...3.e4-e6-4.Nc3-Ne7',
 'Sicilian-Defense-McDonnell-Attack-2...d6-3.Nf3-Nc6',
 'Reti-Opening-Sicilian-Invitation',
 'Pirc-Defense-Main-Line',
 'Modern-Defense-with-1-d4-2.c4-Bg7-3.e4-e6-4.Nc3',
 'Queens-Gambit-Declined-Exchange-Variation-4...exd5-5.Bf4',
 'English-Opening-Carls-Bremen-Smyslov-System-4.Bg2-O-O',
 'Sicilian-Defense-Taimanov-Variation-5.Be3',
 'Sicilian-Defense-Smith-Morra-Gambit-2...cxd4-3.Qxd4-Nc6',
 'Slav-Defense-Modern-Exchange-Variation...6.g3-Bf5-7.Bg2-e6-8.O-O',
 'Sicilian-Defense-Bowdler-Attack-2...e6-3.Nc3',
 'Queens-Pawn-Opening-St-George-Defense-2.c4-b5-3.e4',
 'Sicilian-Defense-Normal-Line-5.Bd3-Nc6-6.Be3',
 'Queens-Gambit-Accepted-Central-Variation-Rubinstein-Defense-4.Nf3-cxd4',
 'Queens-Pawn-Opening-English-Defense-3.Nc3-Bb4',
 'London-System...5.Nbd2-e6-6.c3-Bd6',
 'Alapin-Sicilian-Defense...5.d4-cxd4-6.cxd4-Nc6',
 'Queens-Gambit-Declined-Queens-Knight-Variation-3...Bb4-4.a3-Bxc3-5.bxc3',
 'Alapin-Sicilian-Defense-2...e6-3.d4-cxd4-4.cxd4-d5',
 'Kings-Indian-Defense-Normal-Variation...5.Nf3-O-O-6.h3-Nbd7-7.Be3',
 'Nimzowitsch-Larsen-Attack-Indian-Variation-2.Bb2-e6',
 'Queens-Gambit-Accepted-Central-Variation-Modern-Defense-4.Nf3',
 'Sicilian-Defense-Open-Pelikan-and-Sveshnikov-Exchange-Variation-6...bxc6',
 'Sicilian-Defense-McDonnell-Attack-2...Nc6',
 'Sicilian-Defense-Kramnik-Variation-3...Nc6-4.Nc3-Nf6',
 'Queens-Gambit-Declined-Exchange-Positional-Line...6.e3-h6-7.Bh4-Be7-8.Bd3',
 'Queens-Gambit-Declined-Semi-Tarrasch-Main-Line-Exchange-Variation-6...Nxc3-7.bxc3',
 'Kings-Indian-Defense-Normal-Variation-4.e4',
 'Closed-Sicilian-Defense-Fianchetto-Variation...5.d3-d6-6.Be3-Nf6-7.h3',
 'Old-Indian-Defense-Ukrainian-Two-Knights-Main-Line-8.d5',
 'Queens-Pawn-Opening-Krause-Variation...4.Bf4-Nc6-5.e3-Nf6-6.Bd3',
 'London-System-3...c5-4.e3-Nc6',
 'Queens-Gambit-Declined-Albin-Countergambit-3.dxe5-d4-4.Nf3-Nc6',
 'Sicilian-Defense-Cowboy-Attack-2...Nc6-3.Bb2-d6-4.Bb5',
 'Queens-Pawn-Opening-Horwitz-Defense...3.c4-Nf6-4.Nc3-Bb4-5.g3',
 'Sicilian-Defense-Canal-Attack-3...Nc6-4.O-O-Nf6-5.Re1',
 'Modern-Defense...4.Nf3-Nc6-5.d5-Ne5-6.Nxe5',
 'Slav-Defense-Modern-Three-Knights-Variation-4...Bf5',
 'Kings-Fianchetto-Opening-Sicilian-Invitation-2.Bg2-Nc6-3.d3',
 'Sicilian-Defense-French-Variation...4.Bg2-d5-5.exd5-exd5',
 'Queens-Pawn-Opening-Krause-Variation-3.e3-Nc6-4.c4',
 'Closed-Sicilian-Defense-Traditional-Line-3.Nf3-d6-4.Bb5',
 'Old-Indian-Defense-Janowski-Variation-4.Nf3',
 'Queens-Gambit-Declined-Exchange-Positional-Line-5...c6-6.e3-Bf5',
 'Closed-Sicilian-Defense-2...e6-3.d3-Nc6',
 'French-Defense-Advance-Paulsen-Attack-5...cxd4-6.cxd4',
 'Polish-Opening-Kings-Indian-Defense',
 'Queens-Gambit-Declined-Albin-Countergambit',
 'Alekhines-Defense-Maroczy-Variation',
 'Sicilian-Defense-French-Variation-3.d3-Nc6',
 'Grob-Opening-Grob-Gambit-with-2-Bg2',
 'Indian-Game-2.c4',
 'Queens-Gambit-Declined-Exchange-Positional-Line-5...c6-6.Nf3',
 'Sicilian-Defense-Four-Knights-Variation-6.Bg5',
 'Queens-Gambit-Declined-Chigorin-Defense-3.Nc3-dxc4',
 'Indian-Game',
 'Tarrasch-Defense-Two-Knights-Variation-5...Nc6-6.Bf4',
 'Sicilian-Defense-Four-Knights-Variation-6.Nxc6-bxc6',
 'English-Opening-Kings-English-Nimzowitsch-Variation-2...Nc6-3.d4-exd4-4.Nxd4',
 'English-Opening-Symmetrical-Fianchetto-Variation...4.cxd5-Nxd5-5.Bg2-Nxc3',
 'Queens-Gambit-Declined-Chigorin-Janowski-Variation-4...Bg4',
 'Queens-Pawn-Opening-Accelerated-London-System-2...Nf6',
 'Kings-Indian-Defense-Accelerated-Averbakh-Variation-5...O-O',
 'Reti-Opening-1...Nf6-2.a4',
 'Queens-Gambit-Declined-Chigorin-Defense-3.Nc3-Nf6',
 'Kings-Indian-Defense-Accelerated-Averbakh-Variation',
 'Queens-Pawn-Opening-Anglo-Slav-Opening-3.Nc3',
 'Queens-Gambit-Declined-Exchange-Variation-4...Nxd5',
 'English-Defense-2.c4-Bb7-3.Nc3',
 'Grunfeld-Defense-Exchange-Variation-5.Nf3-Bg7-6.e4',
 'Queens-Pawn-Opening-Pseudo-Catalan-Variation...5.O-O-e6-6.c4-Nbd7',
 'Indian-Game-Tartakower-Attack-2...d5-3.Bg2-c6',
 'Queens-Gambit-Accepted-Central-Variation-Greco-Variation-4.a4',
 'English-Opening-Mikenas-Carls-Variation-3...d6-4.d4',
 'Polish-Opening-1...Nf6-2.Bb2-e6-3.b5',
 'Queens-Gambit-Accepted-Central-Variation-Alekhine-System-4.Nc3',
 nan,
 'Queens-Gambit-Declined-Modern-Variation...5.cxd5-Nxd5-6.Bxe7-Qxe7',
 'Sicilian-Defense-French-Variation...5.Bg2-Nf6-6.O-O-Be7',
 'Tarrasch-Defense-4.Nf3-cxd4-5.Nxd4',
 'Queens-Gambit-Declined-Modern-Variation-4...c6-5.cxd5',
 'Kings-Fianchetto-Opening-1...e5-2.Bg2-d5',
 'Slav-Defense-Modern-Line-3...Nf6-4.g3-Bg4-5.Bg2',
 'Queens-Gambit-Accepted-Central-Variation-McDonnell-Defense-4.Nf3-exd4-5.Bxc4',
 'Queens-Gambit-Declined-Baltic-Defense-3.Nc3',
 'Modern-Defense-with-1-d4-2.c4',
 'Indian-Game-Fantasy-Variation-2...d5',
 'Queens-Gambit-Declined-Semi-Tarrasch-Pillsbury-Variation',
 'Sicilian-Defense-2.Nf3-d6-3.Bc4-e6',
 'Queens-Gambit-Declined-Modern-Variation-4...Be7-5.e3-Nbd7',
 'Birds-Opening-Dutch-Variation-2.Nf3-c5-3.g3-Nc6-4.Bg2',
 'Kings-Indian-Defense-Normal-Variation...6.h3-c5-7.d5-a6',
 'Queens-Pawn-Opening-Chigorin-Variation-2...Nf6-3.Bf4-e6-4.Nb5',
 'Queens-Gambit-Accepted-Central-Variation-Alekhine-System-4.e5-Nd5-5.Bxc4',
 'Sicilian-Defense-2.Nf3-d6-3.g3-Nc6-4.Bg2',
 'Queens-Gambit-Declined-Modern-Variation-4...Be7-5.e3-c6',
 'Sicilian-Defense-French-Variation-3.d3',
 'Nimzo-Indian-Defense-Leningrad-Variation',
 'Indian-Game-2.e3-e6',
 'French-Defense-Advance-Paulsen-Attack-5...cxd4-6.cxd4-Nge7',
 'Four-Knights-Game-Spanish-Variation',
 'Alekhines-Defense',
 'Slav-Defense-Modern-Exchange-Variation-4...cxd5-5.Nc3',
 'Alekhines-Defense-Normal-Variation-3.d4',
 'Old-Benoni-Defense-2.dxc5-e6',
 'Kings-Fianchetto-Opening-1...e5-2.Bg2-Nf6',
 'Kings-Indian-Defense-Normal-Variation-4.e4-O-O-5.Bd3-d6',
 'Queens-Gambit-Accepted-Central-Variation-McDonnell-Defense-4.Nf3-exd4-5.Bxc4-Nc6',
 'Sicilian-Defense-Nimzowitsch-Closed',
 'Sicilian-Defense-Smith-Morra-Gambit',
 'Queens-Gambit-Declined-Traditional-Variation-4...Be7',
 'Sicilian-Defense-Smith-Morra-Accepted-Pin-Defense',
 'Indian-Game-Knights-Variation...4.e3-c5-5.c3-Nc6-6.Bd3',
 'Queens-Gambit-Declined-Marshall-Defense-3.cxd5-Nxd5-4.e4',
 'Torre-Attack-3...Be7-4.e3',
 'Sicilian-Defense-Kramnik-Variation...5.d4-cxd4-6.Nxd4-Bb4',
 'Sicilian-Defense-Open...4.Nxd4-d6-5.Nc3-e5',
 'Queens-Gambit-Declined-Chigorin-Exchange-Variation',
 'Queens-Gambit-Declined-Queens-Knight-Variation-3...f5-4.Nf3-Nf6-5.Bg5',
 'Closed-Sicilian-Defense-2...e6-3.f4-d5',
 'Queens-Gambit-Declined-Orthodox-Botvinnik-Variation-7...c6-8.O-O',
 'Indian-Game-London-System',
 'Nimzo-Indian-Defense-Classical-Variation-4...b6-5.e4-Bb7-6.Bd3',
 'Queens-Gambit-Declined-Semi-Slav-Defense-Accelerated-Move-Order-4.e4',
 'Sicilian-Defense-Nyezhmetdinov-Rossolimo-Attack-3...e6-4.O-O',
 'Queens-Gambit-Declined-Modern-Knight-Defense...7.Bh4-Be7-8.Bd3-O-O',
 'Kings-Indian-Defense-Samisch-Normal-Defense',
 'Scandinavian-Defense-Mieses-Kotrc-Main-Line-4.d4-Nf6-5.Bd2-Bg4',
 'Queens-Pawn-Opening-Pseudo-Catalan-Variation-3...c5',
 'English-Opening-Caro-Kann-Defensive-System...5.Nf3-Nc6-6.d4-Bf5',
 'Tarrasch-Defense-4.Nf3',
 'Queens-Pawn-Opening-Torre-Attack...4.e3-Be7-5.Bd3-O-O',
 'Scandinavian-Defense-2.e5',
 'Kings-Indian-Defense-Makogonov-Variation-5...O-O-6.Bg5-c5',
 'Sicilian-Defense-Open-Accelerated-Dragon-Modern-Variation...7.Bc4-O-O-8.O-O-d6',
 'Sicilian-Defense-Open-Classical-Variation-6.Nxc6-bxc6',
 'Sicilian-Defense-2.d3-d6',
 'Closed-Sicilian-Defense-Portland-Attack-3...d6',
 'Van-Geet-Opening-1...c5-2.Nf3',
 'Kings-Indian-Attack-2...Nc6-3.Bg2',
 'Kings-Fianchetto-Opening...2.Bg2-Nf6-3.d3-d5',
 'Scotch-Game-Scotch-Gambit',
 'Queens-Gambit-Declined-Semi-Slav-Defense-Accelerated-Move-Order-4.Nf3',
 'Queens-Gambit-Accepted-Central-Variation-Modern-Defense-4.Nf3-Bg4',
 'Sicilian-Defense-McDonnell-Attack-2...d5',
 'Queens-Gambit-Declined-Modern-Variation',
 'Kings-Pawn-Opening',
 'French-Defense-Knight-Variation-2...d5-3.e5-c5',
 'Sicilian-Defense-2.d3',
 'Colle-System',
 'Queens-Pawn-Opening-Chigorin-Variation-2...Nf6-3.Bf4-e6',
 'Sicilian-Defense-Nyezhmetdinov-Rossolimo-Attack-3...e6-4.Nc3',
 'Queens-Pawn-Opening-Mikenas-Defense-2.c4',
 'Reti-Opening-Sicilian-Invitation-2.d4-cxd4-3.Nxd4',
 'Queens-Pawn-Opening-English-Rat-Defense-3.Nc3-exd4-4.Qxd4',
 'Sicilian-Defense-2.Nf3-d6-3.Nc3-Nf6',
 'Colle-System-3...e6',
 'Scotch-Game-3...exd4-4.Nxd4-d6',
 'Bishops-Opening-Berlin-Defense',
 'Queens-Gambit-Declined-Baltic-Defense-3.Nc3-e6-4.cxd5',
 'Kings-Gambit-Accepted-Schallopp-Defense-4.Nc3',
 'Vienna-Game-Main-Line-4.fxe5-Nxe4',
 'Sicilian-Defense-Chekhover-Variation-4...Nf6-5.Nc3-Nc6',
 'Kings-Indian-Defense-Normal-Variation-4.e4-O-O-5.Nf3',
 'Sicilian-Defense-2.Nf3-d6-3.Bc4-Nc6',
 'Kings-Indian-Defense-Smyslov-Variation-4...O-O-5.e3-d6',
 'Closed-Sicilian-Defense-2...d6',
 'Kings-Indian-Defense-Normal-Variation-4.e4-d6-5.Nf3',
 'Semi-Slav-Defense-Anti-Meran-Anti-Moscow-Gambit-6...Be7-7.e3-O-O',
 'Sicilian-Defense-Nimzowitsch-Variation-3.d3-Nc6',
 'Queens-Indian-Defense-Kasparov-Variation-4...Bb7-5.Qc2',
 'Sicilian-Defense-2.Nf3-d6-3.Nc3-Nc6',
 'Queens-Gambit-Declined-Baltic-Defense-3.Nc3-e6-4.cxd5-exd5',
 'Queens-Gambit-Accepted-Central-Variation-Modern-Defense',
 'Queens-Gambit-Declined-Queens-Knight-Variation-3...Nc6-4.Nf3-Nf6',
 'Queens-Gambit-Accepted-Old-Variation-3...Nf6-4.Bxc4',
 'Nimzowitsch-Defense-Declined-Williams-Variation-3.d4-Nf6-4.Nc3-Bg4',
 'Reti-Opening-Nimzo-Larsen-Variation-2...d6-3.Bb2-e5',
 'Polish-Opening-1...Nf6-2.Bb2',
 'Scotch-Game-Classical-Variation-5.Nxc6-bxc6',
 'Old-Benoni-Defense-2.e3',
 'Indian-Game-Knights-Variation-2...e6-3.Nc3-d5',
 'Sicilian-Defense-Old-Sicilian-Variation-3.Bc4',
 'Alapin-Sicilian-Defense...4.exd5-exd5-5.Nf3-Nc6-6.Bb5',
 'Sicilian-Defense-Nimzowitsch-Advance-Variation',

In [14]:
import json
from pathlib import Path

OPENINGS_DIC = Path("C:/Users/user/Documents/Stats/Chess-Project/openings_dic.json")
openings_dic = {}
for opening in list(games_df["opening"].unique()):
    openings_dic[opening] = {"simple": None, "variation": None, "ECO": None}
with open(OPENINGS_DIC, "w") as f:
    json.dump(openings_dic, f, indent=4)